//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgGetInfo.proto

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGetInfo")]
    public partial class MsgGetInfo : global::ProtoBuf.IExtensible
    {
        public MsgGetInfo() {}
    
        private string _protoName = @"MsgGetInfo";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"protoName", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(@"MsgGetInfo")]
        public string protoName
        {
            get { return _protoName; }
            set { _protoName = value; }
        }
        private uint _guid = default(uint);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(uint))]
        public uint guid
        {
            get { return _guid; }
            set { _guid = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
