//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/Fixed64Proto.proto
namespace proto.Fixed64Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Fixed64Proto")]
  public partial class Fixed64Proto : global::ProtoBuf.IExtensible
  {
    public Fixed64Proto() {}
    
    private long _value = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"OperationProto")]
    public enum OperationProto
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOYSTICK", Value=0)]
      JOYSTICK = 0
    }
  
}