//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgLockStep.proto
namespace proto.MsgLockStep
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLockStep")]
  public partial class MsgLockStep : global::ProtoBuf.IExtensible
  {
    public MsgLockStep() {}
    
    private int _turn = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int turn
    {
      get { return _turn; }
      set { _turn = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgLockStep.Opts> _opts = new global::System.Collections.Generic.List<MsgLockStep.Opts>();
    [global::ProtoBuf.ProtoMember(2, Name=@"opts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgLockStep.Opts> opts
    {
      get { return _opts; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Opts")]
  public partial class Opts : global::ProtoBuf.IExtensible
  {
    public Opts() {}
    
    private uint _guid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private readonly global::System.Collections.Generic.List<Operation> _operation = new global::System.Collections.Generic.List<Operation>();
    [global::ProtoBuf.ProtoMember(2, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<Operation> operation
    {
      get { return _operation; }
    }
  
    private readonly global::System.Collections.Generic.List<Fixed64> _param = new global::System.Collections.Generic.List<Fixed64>();
    [global::ProtoBuf.ProtoMember(3, Name=@"param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Fixed64> param
    {
      get { return _param; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Fixed64")]
  public partial class Fixed64 : global::ProtoBuf.IExtensible
  {
    public Fixed64() {}
    
    private long _value = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Operation")]
    public enum Operation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOYSTICK", Value=0)]
      JOYSTICK = 0
    }
  
}